version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  deploy-job:
    steps:
      - add_ssh_keys:
          fingerprints:
            77:f8:4a:24:59:88:ca:0e:4e:86:38:af:f4:11:9e:b9
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
          command: |
            pip install pytest
            pip install mock
            pip install boto3
            pip install coverage
            pip install coveralls
            $HOME/.local/bin/coverage run --source src/ -m pytest tests/ -v
            $HOME/.local/bin/coverage report
            $HOME/.local/bin/coverage html 
            coveralls
          name: Test
      - store_artifacts:
          path: htmlcov    
workflows:
  main:
    jobs:
      - deploy-job
      - build-and-test 
